version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  openmetadata_server:
    image: openmetadata/server:${OM_VERSION}
    depends_on:
      - mysql
      - elasticsearch
      - kafka
    environment:
      OPENMETADATA__DATABASE__HOST: mysql
      OPENMETADATA__DATABASE__USERNAME: ${MYSQL_USER}
      OPENMETADATA__DATABASE__PASSWORD: ${MYSQL_PASSWORD}
      OPENMETADATA__DATABASE__DB: ${MYSQL_DB}
      OPENMETADATA__SEARCH__ELASTICSEARCH__HOST: elasticsearch
      OPENMETADATA__SEARCH__ELASTICSEARCH__PORT: 9200
      OPENMETADATA__MESSAGING__KAFKA__BROKER_SERVERS: kafka:9092
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:8585"

  openmetadata_ingestion:
    image: openmetadata/ingestion:${OM_VERSION}
    depends_on:
      - openmetadata_server
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      OM_SERVER_HOST: openmetadata_server
      OM_SERVER_PORT: 8585

volumes:
  mysql_data:
  es_data:
